import type { EngineName } from "../core/types.js";

export function buildMvMzRuntimePlugin(engine: EngineName, targetLang: string): string {
  return PLUGIN
    .replace("__RPGMTRANS_ENGINE__", JSON.stringify(engine))
    .replace("__RPGMTRANS_TARGET_LANG__", JSON.stringify(targetLang));
}

const PLUGIN = String.raw`/*:
 * @target MV MZ
 * @plugindesc RPGMTransRuntime bridge. Records displayed text and hot-loads local translations.
 *
 * This plugin is generated by RPGMTransCompiler. It never calls external APIs.
 */
(function() {
  "use strict";

  var ENGINE = __RPGMTRANS_ENGINE__;
  var TARGET_LANG = __RPGMTRANS_TARGET_LANG__;
  var PROTOCOL = "1";
  var CACHE_RELOAD_MS = 250;

  var fs = null;
  var path = null;
  try {
    fs = require("fs");
    path = require("path");
  } catch (error) {
    return;
  }

  var root = process.cwd();
  var runtimeDir = path.join(root, "RPGMTransRuntime");
  var requestDir = path.join(runtimeDir, "requests");
  var cacheFile = path.join(runtimeDir, "cache", "translations.rtc");
  var diagDir = path.join(runtimeDir, "diag");
  var sessionFile = path.join(requestDir, "session-" + Date.now() + "-" + Math.floor(Math.random() * 1000000) + ".rtlog");
  var cacheMtime = 0;
  var lastCacheCheck = 0;
  var translations = Object.create(null);
  var seen = Object.create(null);
  var dirtyRefresh = false;
  var inDraw = false;
  var activeMessageWindow = null;

  function mkdirp(dir) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  }

  mkdirp(requestDir);
  mkdirp(path.dirname(cacheFile));
  mkdirp(diagDir);
  if (!fs.existsSync(cacheFile)) fs.writeFileSync(cacheFile, "# RPGMTransRuntime cache v1\n", "utf8");
  fs.appendFileSync(sessionFile, "# RPGMTransRuntime requests v1\n", "utf8");

  function runtimeHash(input) {
    var bytes = Buffer.from(String(input), "utf8");
    var seeds = [0x811c9dc5, 0x1f123bb5, 0x9e3779b9, 0x85ebca6b];
    var out = [];
    for (var s = 0; s < seeds.length; s++) {
      var hash = seeds[s] >>> 0;
      for (var i = 0; i < bytes.length; i++) {
        hash ^= bytes[i];
        hash = Math.imul(hash, 0x01000193) >>> 0;
      }
      out.push(("00000000" + hash.toString(16)).slice(-8));
    }
    return out.join("");
  }

  function hex(input) {
    return Buffer.from(String(input), "utf8").toString("hex");
  }

  function unhex(input) {
    return Buffer.from(String(input), "hex").toString("utf8");
  }

  function normalizeText(input) {
    return String(input == null ? "" : input).replace(/\r\n/g, "\n").replace(/\r/g, "\n").replace(/[ \t]+/g, " ").trim();
  }

  function shouldRecordText(input) {
    var text = normalizeText(input);
    if (!text) return false;
    if (text.indexOf("[" + TARGET_LANG + "]") === 0) return false;
    var ascii = /^[\x00-\x7f]+$/.test(text);
    if (ascii && text.length === 1) return false;
    if (ascii && !/[A-Za-z]/.test(text)) return false;
    return true;
  }

  function placeholderSignature(input) {
    var text = String(input);
    var re = /[\\\x1b¥￥][VvNnPpCcIiSs]\[\d+\]|[\\\x1b¥￥][A-Za-z]{1,12}\[[^\]\r\n]{0,80}\]|[\\\x1b¥￥][Gg.!|><^{}\\]|#\{[^}]*\}|\$\{[^}]*\}|%(?:\d+\$)?[-+#0 ]*(?:\d+|\*)?(?:\.(?:\d+|\*))?[bcdeEufFgGosxX]|%\d+|<\/?[A-Za-z][^>\n]{0,120}>|\{\{[^{}\n]{1,80}\}\}|\{[A-Za-z_][A-Za-z0-9_.-]{0,80}\}/g;
    var out = [];
    var match;
    while ((match = re.exec(text))) out.push(hex(match[0]));
    return out.length ? out.join(",") : "none";
  }

  function textKey(source) {
    var normalized = normalizeText(source);
    return "tk_" + runtimeHash([
      "rpgmtrans-runtime-text-v1",
      ENGINE,
      TARGET_LANG,
      normalized,
      placeholderSignature(normalized)
    ].join("\n"));
  }

  function surfaceKey(source, hook, scene, windowName, width, align) {
    var tk = textKey(source);
    return "sk_" + runtimeHash([
      "rpgmtrans-runtime-surface-v1",
      tk,
      hook,
      scene,
      windowName,
      String(width),
      align || ""
    ].join("\n"));
  }

  function currentSceneName() {
    try {
      return SceneManager && SceneManager._scene && SceneManager._scene.constructor ? SceneManager._scene.constructor.name : "";
    } catch (error) {
      return "";
    }
  }

  function windowName(win) {
    try {
      return win && win.constructor ? win.constructor.name : "";
    } catch (error) {
      return "";
    }
  }

  function parseCache() {
    var map = Object.create(null);
    if (!fs.existsSync(cacheFile)) return map;
    var lines = fs.readFileSync(cacheFile, "utf8").split(/\r?\n/);
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      if (!line || line.charAt(0) === "#") continue;
      var parts = line.split("\t");
      if (parts.length < 11 || parts[0] !== "1") continue;
      var key = parts[2];
      var sourceHex = parts[7];
      var targetHex = parts[8];
      map[key] = { sourceHex: sourceHex, target: unhex(targetHex) };
    }
    return map;
  }

  function reloadCacheIfNeeded(force) {
    var now = Date.now();
    if (!force && now - lastCacheCheck < CACHE_RELOAD_MS) return;
    lastCacheCheck = now;
    try {
      var stat = fs.existsSync(cacheFile) ? fs.statSync(cacheFile) : null;
      var mtime = stat ? stat.mtimeMs : 0;
      if (!force && mtime === cacheMtime) return;
      cacheMtime = mtime;
      translations = parseCache();
      dirtyRefresh = true;
    } catch (error) {
      try { fs.appendFileSync(path.join(diagDir, "plugin.log"), String(error.stack || error) + "\n", "utf8"); } catch (_) {}
    }
  }

  function lookup(source, sk, tk) {
    reloadCacheIfNeeded(false);
    var sourceHex = hex(source);
    var surface = translations[sk];
    if (surface && surface.sourceHex === sourceHex) return surface.target;
    var text = translations[tk];
    if (text && text.sourceHex === sourceHex) return text.target;
    return null;
  }

  function lookupProbe(probe, source) {
    if (!probe || !source) return null;
    return lookup(source, probe.surfaceKey, probe.textKey);
  }

  function record(source, hook, win, width, align) {
    var normalized = normalizeText(source);
    if (!shouldRecordText(source)) return { textKey: "", surfaceKey: "", target: null };
    var scene = currentSceneName();
    var wname = windowName(win);
    var tk = textKey(source);
    var sk = surfaceKey(source, hook, scene, wname, width || "", align || "");
    var target = lookup(source, sk, tk);
    if (target != null) return { textKey: tk, surfaceKey: sk, target: target };
    if (!seen[sk]) {
      seen[sk] = true;
      var line = [
        PROTOCOL,
        ENGINE,
        TARGET_LANG,
        tk,
        sk,
        hook,
        scene,
        wname,
        String(width || ""),
        String(align || ""),
        hex(normalized),
        hex(source),
        placeholderSignature(normalized),
        new Date().toISOString()
      ].join("\t") + "\n";
      try { fs.appendFileSync(sessionFile, line, "utf8"); } catch (error) {}
    }
    return { textKey: tk, surfaceKey: sk, target: null };
  }

  function safeRefreshWindows() {
    if (!dirtyRefresh) return;
    dirtyRefresh = false;
    try {
      refreshActiveMessageWindow();
      var scene = SceneManager._scene;
      if (!scene || !scene.children) return;
      var stack = scene.children.slice();
      while (stack.length) {
        var node = stack.shift();
        if (!node) continue;
        if (node.children) stack = stack.concat(node.children);
        if (typeof node.refresh === "function") {
          try { node.refresh(); } catch (_) {}
        }
      }
    } catch (error) {}
  }

  function refreshActiveMessageWindow() {
    var win = activeMessageWindow;
    if (!win || !win._rpgmtransRuntimeMessageSource || !win._rpgmtransRuntimeMessageProbe) return;
    try {
      if (win._rpgmtransRuntimeApplied) return;
      if (win.openness <= 0 && !win.isOpen()) return;
      var source = win._rpgmtransRuntimeMessageSource;
      var target = lookupProbe(win._rpgmtransRuntimeMessageProbe, source);
      if (target == null) return;
      win._rpgmtransRuntimeApplied = true;
      repaintMessageWindow(win, target);
    } catch (error) {
      try { fs.appendFileSync(path.join(diagDir, "plugin.log"), String(error.stack || error) + "\n", "utf8"); } catch (_) {}
    }
  }

  function repaintMessageWindow(win, target) {
    if (!win || !win.contents || typeof win.newPage !== "function") return;
    if (win._choiceWindow && win._choiceWindow.active) return;
    if (win._numberWindow && win._numberWindow.active) return;
    if (win._itemWindow && win._itemWindow.active) return;
    var oldPause = win.pause;
    var oldShowFast = win._showFast;
    var textState = {
      index: 0,
      text: typeof win.convertEscapeCharacters === "function" ? win.convertEscapeCharacters(String(target)) : String(target)
    };
    inDraw = true;
    try {
      win.pause = false;
      if (typeof win.updatePlacement === "function") win.updatePlacement();
      if (typeof win.updateBackground === "function") win.updateBackground();
      win._textState = textState;
      win.newPage(textState);
      if (typeof win.open === "function") win.open();
      win._showFast = true;
      if (typeof win.updateMessage === "function") {
        var guard = 0;
        while (win._textState && guard < 256) {
          guard++;
          if (!win.updateMessage()) break;
          if (win.pause || win._waitCount > 0) break;
        }
      }
    } finally {
      win._showFast = oldShowFast;
      win.pause = oldPause && !win._textState;
      inDraw = false;
    }
  }

  var _SceneManager_updateMain = SceneManager.updateMain;
  SceneManager.updateMain = function() {
    reloadCacheIfNeeded(false);
    safeRefreshWindows();
    return _SceneManager_updateMain.apply(this, arguments);
  };

  if (typeof Window_Base !== "undefined") {
    var _drawText = Window_Base.prototype.drawText;
    Window_Base.prototype.drawText = function(text, x, y, maxWidth, align) {
      if (inDraw) return _drawText.apply(this, arguments);
      var probe = record(text, "drawText", this, maxWidth, align || "");
      inDraw = true;
      try {
        return _drawText.call(this, probe.target != null ? probe.target : text, x, y, maxWidth, align);
      } finally {
        inDraw = false;
      }
    };

    var _drawTextEx = Window_Base.prototype.drawTextEx;
    Window_Base.prototype.drawTextEx = function(text, x, y) {
      if (inDraw) return _drawTextEx.apply(this, arguments);
      var width = this.contents ? this.contents.width : "";
      var probe = record(text, "drawTextEx", this, width, "");
      inDraw = true;
      try {
        return _drawTextEx.call(this, probe.target != null ? probe.target : text, x, y);
      } finally {
        inDraw = false;
      }
    };
  }

  if (typeof Window_Message !== "undefined") {
    var _startMessage = Window_Message.prototype.startMessage;
    Window_Message.prototype.startMessage = function() {
      try {
        activeMessageWindow = this;
        var text = $gameMessage && $gameMessage.allText ? $gameMessage.allText() : "";
        var width = this.contents ? this.contents.width : "";
        var probe = record(text, "message", this, width, "");
        this._rpgmtransRuntimeMessageSource = text;
        this._rpgmtransRuntimeMessageProbe = probe;
        this._rpgmtransRuntimeApplied = probe.target != null;
        if (probe.target != null && $gameMessage && $gameMessage._texts) {
          $gameMessage._texts = String(probe.target).split("\n");
        }
      } catch (error) {}
      return _startMessage.apply(this, arguments);
    };

    var _terminateMessage = Window_Message.prototype.terminateMessage;
    Window_Message.prototype.terminateMessage = function() {
      if (activeMessageWindow === this) activeMessageWindow = null;
      this._rpgmtransRuntimeMessageSource = null;
      this._rpgmtransRuntimeMessageProbe = null;
      this._rpgmtransRuntimeApplied = false;
      return _terminateMessage.apply(this, arguments);
    };
  }

  if (typeof Bitmap !== "undefined") {
    var _bitmapDrawText = Bitmap.prototype.drawText;
    Bitmap.prototype.drawText = function(text, x, y, maxWidth, lineHeight, align) {
      if (inDraw) return _bitmapDrawText.apply(this, arguments);
      var probe = record(text, "bitmap", this, maxWidth, align || "");
      return _bitmapDrawText.call(this, probe.target != null ? probe.target : text, x, y, maxWidth, lineHeight, align);
    };
  }

  reloadCacheIfNeeded(true);
})();`;
