export function buildRenpyRuntimeScript(targetLang: string): string {
  return SCRIPT.replace("__RPGMTRANS_TARGET_LANG__", JSON.stringify(targetLang));
}

const SCRIPT = String.raw`# RPGMTransRuntime bridge for Ren'Py.
# Generated by RPGMTransCompiler. It never calls external APIs.

init -999 python:
    import os
    import re
    import time
    import binascii
    import io
    try:
        basestring
    except NameError:
        basestring = str
    try:
        unicode
    except NameError:
        unicode = str

    RPGMTRANS_ENGINE = "RENPY"
    RPGMTRANS_TARGET_LANG = __RPGMTRANS_TARGET_LANG__
    RPGMTRANS_PROTOCOL = "1"
    RPGMTRANS_CACHE_RELOAD_SECONDS = 0.25

    def _rpgmtrans_game_root():
        try:
            return os.path.dirname(config.gamedir)
        except Exception:
            try:
                return config.basedir
            except Exception:
                return os.getcwd()

    _rpgmtrans_root = _rpgmtrans_game_root()
    _rpgmtrans_runtime = os.path.join(_rpgmtrans_root, "RPGMTransRuntime")
    _rpgmtrans_request_dir = os.path.join(_rpgmtrans_runtime, "requests")
    _rpgmtrans_cache_file = os.path.join(_rpgmtrans_runtime, "cache", "translations.rtc")
    _rpgmtrans_diag_dir = os.path.join(_rpgmtrans_runtime, "diag")
    _rpgmtrans_session_file = os.path.join(_rpgmtrans_request_dir, "session-%d-%d.rtlog" % (int(time.time() * 1000), os.getpid()))
    _rpgmtrans_cache_mtime = 0
    _rpgmtrans_last_cache_check = 0
    _rpgmtrans_translations = {}
    _rpgmtrans_seen = set()

    def _rpgmtrans_makedirs(path):
        if not os.path.isdir(path):
            try:
                os.makedirs(path)
            except OSError:
                pass

    _rpgmtrans_makedirs(_rpgmtrans_request_dir)
    _rpgmtrans_makedirs(os.path.dirname(_rpgmtrans_cache_file))
    _rpgmtrans_makedirs(_rpgmtrans_diag_dir)
    if not os.path.exists(_rpgmtrans_cache_file):
        open(_rpgmtrans_cache_file, "a").write("# RPGMTransRuntime cache v1\n")
    open(_rpgmtrans_session_file, "a").write("# RPGMTransRuntime requests v1\n")

    def _rpgmtrans_text(value):
        if value is None:
            return ""
        try:
            if isinstance(value, unicode):
                return value
        except Exception:
            pass
        try:
            return unicode(value)
        except Exception:
            return str(value)

    def _rpgmtrans_utf8(value):
        text = _rpgmtrans_text(value)
        try:
            return text.encode("utf-8")
        except Exception:
            return str(text).encode("utf-8")

    def _rpgmtrans_hex(value):
        return binascii.hexlify(_rpgmtrans_utf8(value)).decode("ascii")

    def _rpgmtrans_unhex(value):
        try:
            return binascii.unhexlify(value).decode("utf-8")
        except Exception:
            return ""

    def _rpgmtrans_normalize(value):
        text = _rpgmtrans_text(value).replace("\r\n", "\n").replace("\r", "\n")
        text = re.sub(r"[ \t]+", " ", text)
        return text.strip()

    def _rpgmtrans_hash(value):
        data = _rpgmtrans_utf8(value)
        seeds = [0x811c9dc5, 0x1f123bb5, 0x9e3779b9, 0x85ebca6b]
        out = []
        for seed in seeds:
            h = seed
            for b in bytearray(data):
                h ^= b
                h = (h * 0x01000193) & 0xffffffff
            out.append(("%08x" % h)[-8:])
        return "".join(out)

    _rpgmtrans_placeholder_re = re.compile(r"(\[[A-Za-z_][A-Za-z0-9_.!?:|+\-]{0,120}\]|\{\/?[A-Za-z][A-Za-z0-9_]*(?:=[^{}\r\n]{0,120})?\}|%\([^)]+\)[#0 +\-]?\d*(?:\.\d+)?[a-zA-Z]|%(?:\d+\$)?[-+#0 ]*(?:\d+|\*)?(?:\.(?:\d+|\*))?[bcdeEufFgGosxX])")

    def _rpgmtrans_placeholder_signature(value):
        parts = []
        for match in _rpgmtrans_placeholder_re.finditer(_rpgmtrans_text(value)):
            parts.append(_rpgmtrans_hex(match.group(0)))
        return ",".join(parts) if parts else "none"

    def _rpgmtrans_text_key(source):
        normalized = _rpgmtrans_normalize(source)
        return "tk_" + _rpgmtrans_hash("\n".join([
            "rpgmtrans-runtime-text-v1",
            RPGMTRANS_ENGINE,
            RPGMTRANS_TARGET_LANG,
            normalized,
            _rpgmtrans_placeholder_signature(normalized)
        ]))

    def _rpgmtrans_surface_key(source, hook, scene, window_name, width, align):
        tk = _rpgmtrans_text_key(source)
        return "sk_" + _rpgmtrans_hash("\n".join([
            "rpgmtrans-runtime-surface-v1",
            tk,
            hook or "",
            scene or "",
            window_name or "",
            str(width or ""),
            align or ""
        ]))

    def _rpgmtrans_should_record(source):
        text = _rpgmtrans_normalize(source)
        if not text:
            return False
        if text.startswith("[" + RPGMTRANS_TARGET_LANG + "]"):
            return False
        if len(text) == 1 and ord(text[0]) < 128:
            return False
        if all(ord(ch) < 128 for ch in text) and not re.search(r"[A-Za-z]", text):
            return False
        return True

    def _rpgmtrans_parse_cache():
        out = {}
        if not os.path.exists(_rpgmtrans_cache_file):
            return out
        try:
            for line in io.open(_rpgmtrans_cache_file, "r", encoding="utf-8"):
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) < 11 or parts[0] != "1":
                    continue
                out[parts[2]] = {"sourceHex": parts[7], "target": _rpgmtrans_unhex(parts[8])}
        except TypeError:
            for line in open(_rpgmtrans_cache_file, "r"):
                line = line.decode("utf-8").strip() if hasattr(line, "decode") else line.strip()
                parts = line.split("\t")
                if len(parts) >= 11 and parts[0] == "1":
                    out[parts[2]] = {"sourceHex": parts[7], "target": _rpgmtrans_unhex(parts[8])}
        except Exception:
            pass
        return out

    def _rpgmtrans_reload_cache(force=False):
        global _rpgmtrans_cache_mtime, _rpgmtrans_last_cache_check, _rpgmtrans_translations
        now = time.time()
        if not force and now - _rpgmtrans_last_cache_check < RPGMTRANS_CACHE_RELOAD_SECONDS:
            return
        _rpgmtrans_last_cache_check = now
        try:
            mtime = os.path.getmtime(_rpgmtrans_cache_file) if os.path.exists(_rpgmtrans_cache_file) else 0
            if not force and mtime == _rpgmtrans_cache_mtime:
                return
            _rpgmtrans_cache_mtime = mtime
            _rpgmtrans_translations = _rpgmtrans_parse_cache()
            try:
                renpy.restart_interaction()
            except Exception:
                pass
        except Exception:
            pass

    def _rpgmtrans_lookup(source, sk, tk):
        _rpgmtrans_reload_cache(False)
        source_hex = _rpgmtrans_hex(source)
        for key in (sk, tk):
            entry = _rpgmtrans_translations.get(key)
            if entry and entry.get("sourceHex") == source_hex:
                return entry.get("target")
        return None

    def _rpgmtrans_record(source, hook, scene="", window_name="", width="", align=""):
        if not _rpgmtrans_should_record(source):
            return source
        normalized = _rpgmtrans_normalize(source)
        tk = _rpgmtrans_text_key(source)
        sk = _rpgmtrans_surface_key(source, hook, scene, window_name, width, align)
        target = _rpgmtrans_lookup(source, sk, tk)
        if target is not None:
            return target
        if sk not in _rpgmtrans_seen:
            _rpgmtrans_seen.add(sk)
            line = "\t".join([
                RPGMTRANS_PROTOCOL,
                RPGMTRANS_ENGINE,
                RPGMTRANS_TARGET_LANG,
                tk,
                sk,
                hook or "",
                scene or "",
                window_name or "",
                str(width or ""),
                align or "",
                _rpgmtrans_hex(normalized),
                _rpgmtrans_hex(source),
                _rpgmtrans_placeholder_signature(normalized),
                time.strftime("%Y-%m-%dT%H:%M:%S")
            ]) + "\n"
            try:
                io.open(_rpgmtrans_session_file, "a", encoding="utf-8").write(line)
            except Exception:
                pass
        return source

    def _rpgmtrans_translate_value(value, hook):
        if isinstance(value, basestring):
            return _rpgmtrans_record(value, hook)
        return value

    try:
        _rpgmtrans_old_say = renpy.exports.say
        def _rpgmtrans_say(who, what, *args, **kwargs):
            return _rpgmtrans_old_say(who, _rpgmtrans_translate_value(what, "say"), *args, **kwargs)
        renpy.exports.say = _rpgmtrans_say
        renpy.say = _rpgmtrans_say
    except Exception:
        pass

    try:
        _rpgmtrans_old_menu = renpy.exports.menu
        def _rpgmtrans_menu(items, *args, **kwargs):
            converted = []
            for item in items:
                try:
                    label = item[0]
                    if isinstance(label, basestring):
                        item = (_rpgmtrans_record(label, "menu"),) + tuple(item[1:])
                except Exception:
                    pass
                converted.append(item)
            return _rpgmtrans_old_menu(converted, *args, **kwargs)
        renpy.exports.menu = _rpgmtrans_menu
    except Exception:
        pass

    try:
        import renpy.text.text as _rpgmtrans_text_module
        _rpgmtrans_old_text_init = _rpgmtrans_text_module.Text.__init__
        def _rpgmtrans_text_init(self, text, *args, **kwargs):
            return _rpgmtrans_old_text_init(self, _rpgmtrans_translate_value(text, "text"), *args, **kwargs)
        _rpgmtrans_text_module.Text.__init__ = _rpgmtrans_text_init
    except Exception:
        pass

    _rpgmtrans_reload_cache(True)
`;
