export function buildTyranoRuntimePlugin(targetLang: string): string {
  return PLUGIN.replace("__RPGMTRANS_TARGET_LANG__", JSON.stringify(targetLang));
}

const PLUGIN = String.raw`// RPGMTransRuntime bridge for TyranoScript.
// Generated by RPGMTransCompiler. It never calls external APIs.
(function() {
  "use strict";

  var ENGINE = "TYRANO";
  var TARGET_LANG = __RPGMTRANS_TARGET_LANG__;
  var PROTOCOL = "1";
  var CACHE_RELOAD_MS = 250;

  var fs = null;
  var path = null;
  try {
    fs = require("fs");
    path = require("path");
  } catch (error) {
    return;
  }

  var root = process.cwd();
  try {
    if (process.execPath) root = path.dirname(process.execPath);
  } catch (_) {}
  var runtimeDir = path.join(root, "RPGMTransRuntime");
  var requestDir = path.join(runtimeDir, "requests");
  var cacheFile = path.join(runtimeDir, "cache", "translations.rtc");
  var diagDir = path.join(runtimeDir, "diag");
  var sessionFile = path.join(requestDir, "session-" + Date.now() + "-" + Math.floor(Math.random() * 1000000) + ".rtlog");
  var cacheMtime = 0;
  var lastCacheCheck = 0;
  var translations = Object.create(null);
  var seen = Object.create(null);
  var pendingDialogue = null;

  function mkdirp(dir) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  }

  mkdirp(requestDir);
  mkdirp(path.dirname(cacheFile));
  mkdirp(diagDir);
  if (!fs.existsSync(cacheFile)) fs.writeFileSync(cacheFile, "# RPGMTransRuntime cache v1\n", "utf8");
  fs.appendFileSync(sessionFile, "# RPGMTransRuntime requests v1\n", "utf8");
  logDiag("runtime loaded: " + sessionFile);

  function logDiag(message) {
    try { fs.appendFileSync(path.join(diagDir, "plugin.log"), "[" + new Date().toISOString() + "] " + message + "\n", "utf8"); } catch (_) {}
  }

  function runtimeHash(input) {
    var bytes = makeBuffer(String(input), "utf8");
    var seeds = [0x811c9dc5, 0x1f123bb5, 0x9e3779b9, 0x85ebca6b];
    var out = [];
    for (var s = 0; s < seeds.length; s++) {
      var hash = seeds[s] >>> 0;
      for (var i = 0; i < bytes.length; i++) {
        hash ^= bytes[i];
        hash = imul32(hash, 0x01000193) >>> 0;
      }
      out.push(("00000000" + hash.toString(16)).slice(-8));
    }
    return out.join("");
  }

  function imul32(a, b) {
    if (typeof Math.imul === "function") return Math.imul(a, b);
    var ah = (a >>> 16) & 0xffff;
    var al = a & 0xffff;
    var bh = (b >>> 16) & 0xffff;
    var bl = b & 0xffff;
    return (al * bl + (((ah * bl + al * bh) & 0xffff) << 16)) | 0;
  }

  function hex(input) {
    return makeBuffer(String(input), "utf8").toString("hex");
  }

  function unhex(input) {
    return makeBuffer(String(input), "hex").toString("utf8");
  }

  function makeBuffer(input, encoding) {
    if (typeof Buffer.from === "function") return Buffer.from(input, encoding);
    return new Buffer(input, encoding);
  }

  function normalizeText(input) {
    return String(input == null ? "" : input).replace(/\r\n/g, "\n").replace(/\r/g, "\n").replace(/[ \t]+/g, " ").trim();
  }

  function stripTyranoDisplayTags(input) {
    return normalizeText(String(input == null ? "" : input)
      .replace(/\[(?:p|r|l|cm|ct|clearfix|resetfont|resetconfig|endlink)\b[^\]\r\n]*\]/gi, "")
      .replace(/^\s*@(?:p|r|l|cm|ct)\b[^\r\n]*$/gim, ""));
  }

  function shouldRecordText(input) {
    var text = normalizeText(input);
    if (!text) return false;
    if (text.indexOf("[" + TARGET_LANG + "]") === 0) return false;
    if (looksLikeCode(text)) return false;
    var ascii = /^[\x00-\x7f]+$/.test(text);
    if (ascii && text.length === 1) return false;
    if (ascii && !/[A-Za-z]/.test(text)) return false;
    return true;
  }

  function looksLikeCode(text) {
    if (/^(?:if|for|while|switch)\s*\(.+\)\s*\{?$/.test(text)) return true;
    if (/^(?:var|let|const|return|else)\b/.test(text) && /[;{}()=]/.test(text)) return true;
    if (/^(?:tf|sf|mp|f|TYRANO|tyrano|this|kag)\b(?:[.\[])/.test(text) && /[;{}()=]/.test(text)) return true;
    if (/^[A-Za-z_$][\w$]*(?:[.\[][^\s]*)+\s*=\s*[^=].*;?$/.test(text)) return true;
    return false;
  }

  function placeholderSignature(input) {
    var text = String(input);
    var re = /\[[A-Za-z_][A-Za-z0-9_]*(?:\s+[^\]\r\n]{0,240})?\]|\{\/?[A-Za-z][A-Za-z0-9_]*(?:=[^{}\r\n]{0,120})?\}|[\\\x1b¥￥][VvNnPpCcIiSs]\[\d+\]|[\\\x1b¥￥][A-Za-z]{1,12}\[[^\]\r\n]{0,80}\]|[\\\x1b¥￥][Gg.!|><^{}\\]|#\{[^}]*\}|\$\{[^}]*\}|%(?:\d+\$)?[-+#0 ]*(?:\d+|\*)?(?:\.(?:\d+|\*))?[bcdeEufFgGosxX]|%\d+|<\/?[A-Za-z][^>\n]{0,120}>|\{\{[^{}\n]{1,80}\}\}/g;
    var out = [];
    var match;
    while ((match = re.exec(text))) out.push(hex(match[0]));
    return out.length ? out.join(",") : "none";
  }

  function textKey(source) {
    var normalized = normalizeText(source);
    return "tk_" + runtimeHash([
      "rpgmtrans-runtime-text-v1",
      ENGINE,
      TARGET_LANG,
      normalized,
      placeholderSignature(normalized)
    ].join("\n"));
  }

  function surfaceKey(source, hook, scene, windowName, width, align) {
    var tk = textKey(source);
    return "sk_" + runtimeHash([
      "rpgmtrans-runtime-surface-v1",
      tk,
      hook,
      scene || "",
      windowName || "",
      String(width || ""),
      align || ""
    ].join("\n"));
  }

  function parseCache() {
    var map = Object.create(null);
    if (!fs.existsSync(cacheFile)) return map;
    var lines = fs.readFileSync(cacheFile, "utf8").split(/\r?\n/);
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      if (!line || line.charAt(0) === "#") continue;
      var parts = line.split("\t");
      if (parts.length < 11 || parts[0] !== "1") continue;
      map[parts[2]] = { sourceHex: parts[7], target: unhex(parts[8]) };
    }
    return map;
  }

  function reloadCacheIfNeeded(force) {
    var now = Date.now();
    if (!force && now - lastCacheCheck < CACHE_RELOAD_MS) return false;
    lastCacheCheck = now;
    try {
      var stat = fs.existsSync(cacheFile) ? fs.statSync(cacheFile) : null;
      var mtime = stat ? stat.mtimeMs : 0;
      if (!force && mtime === cacheMtime) return false;
      cacheMtime = mtime;
      translations = parseCache();
      return true;
    } catch (error) {
      logDiag(String(error.stack || error));
      return false;
    }
  }

  function lookup(source, sk, tk) {
    reloadCacheIfNeeded(false);
    var sourceHex = hex(source);
    var surface = translations[sk];
    if (surface && surface.sourceHex === sourceHex) return surface.target;
    var text = translations[tk];
    if (text && text.sourceHex === sourceHex) return text.target;
    return null;
  }

  function lookupSources(source, hook) {
    var displaySource = stripTyranoDisplayTags(source);
    var sources = [];
    function push(value) {
      var normalized = normalizeText(value);
      if (!normalized) return;
      for (var i = 0; i < sources.length; i++) {
        if (sources[i] === normalized) return;
      }
      sources.push(normalized);
    }
    push(displaySource);
    if (hook === "text") push(displaySource + "[p]");
    push(source);
    return sources;
  }

  function findCachedTranslation(source, hook, width, align) {
    var sources = lookupSources(source, hook);
    for (var i = 0; i < sources.length; i++) {
      var candidate = sources[i];
      var tk = textKey(candidate);
      var sk = surfaceKey(candidate, hook, "", "", width || "", align || "");
      var target = lookup(candidate, sk, tk);
      if (target != null) {
        return { target: stripTyranoDisplayTags(target), source: candidate, textKey: tk, surfaceKey: sk };
      }
    }
    return null;
  }

  function translateTextResult(source, hook, width, align, options) {
    var requestSource = stripTyranoDisplayTags(source);
    if (!shouldRecordText(requestSource)) return { value: source, hit: false, requestSource: requestSource };
    var hit = findCachedTranslation(requestSource, hook, width, align);
    if (hit) return { value: hit.target, hit: true, requestSource: requestSource };
    if (options && options.recordMiss === false) return { value: source, hit: false, requestSource: requestSource };
    var normalized = normalizeText(requestSource);
    var tk = textKey(requestSource);
    var sk = surfaceKey(requestSource, hook, "", "", width || "", align || "");
    if (!seen[sk]) {
      seen[sk] = true;
      var line = [
        PROTOCOL,
        ENGINE,
        TARGET_LANG,
        tk,
        sk,
        hook,
        "",
        "",
        String(width || ""),
        String(align || ""),
        hex(normalized),
        hex(requestSource),
        placeholderSignature(normalized),
        new Date().toISOString()
      ].join("\t") + "\n";
      try { fs.appendFileSync(sessionFile, line, "utf8"); } catch (error) {}
    }
    return { value: source, hit: false, requestSource: requestSource };
  }

  function translateText(value, hook, options) {
    if (typeof value !== "string") return value;
    return translateTextResult(value, hook || "tyrano", "", "", options).value;
  }

  function rememberPendingDialogue(tagThis, source) {
    var requestSource = stripTyranoDisplayTags(source);
    if (!shouldRecordText(requestSource)) return;
    pendingDialogue = { tag: tagThis, source: requestSource, createdAt: Date.now() };
  }

  function repaintPendingDialogue() {
    if (!pendingDialogue) return;
    if (Date.now() - pendingDialogue.createdAt > 30000) {
      pendingDialogue = null;
      return;
    }
    var hit = findCachedTranslation(pendingDialogue.source, "text", "", "");
    if (!hit) return;
    var target = hit.target;
    var tag = pendingDialogue.tag || {};
    var kag = tag.kag || (window.TYRANO && window.TYRANO.kag);
    if (!kag || typeof kag.getMessageInnerLayer !== "function") return;
    var layer = kag.getMessageInnerLayer();
    if (!layer || !layer.length) return;
    var current = "";
    try { current = normalizeText(typeof layer.text === "function" ? layer.text() : ""); } catch (_) {}
    var expected = normalizeText(pendingDialogue.source);
    if (current && expected && current.indexOf(expected) === -1 && expected.indexOf(current) === -1) return;
    try {
      var paragraph = typeof layer.find === "function" ? layer.find("p").last() : null;
      if (paragraph && paragraph.length && typeof paragraph.empty === "function") {
        paragraph.empty();
        paragraph.text(target);
      } else if (typeof layer.text === "function") {
        layer.text(target);
      }
      if (kag.stat) kag.stat.current_message_str = target;
      pendingDialogue = null;
      logDiag("repainted pending text");
    } catch (error) {
      logDiag("repaint pending text failed: " + String(error && (error.stack || error.message) || error));
    }
  }

  function patchTyranoTags() {
    var patchedAny = false;
    function patchTagSet(tags, sourceName) {
      if (!tags) return false;
      var changed = false;
      ["text", "ptext", "glink", "button", "link", "chara_name", "chara_ptext"].forEach(function(name) {
        var tag = tags[name];
        if (!tag || tag._rpgmtransPatched || typeof tag.start !== "function") return;
        var oldStart = tag.start;
        tag.start = function(pm) {
          try {
            if (pm) {
              if (name === "text" && typeof pm.val === "string") {
                var textResult = translateTextResult(pm.val, "text", "", "", {});
                if (textResult.hit) {
                  pm.val = textResult.value;
                  pendingDialogue = null;
                } else {
                  rememberPendingDialogue(this, pm.val);
                }
              }
              if (typeof pm.text === "string") pm.text = translateText(pm.text, name);
              if ((name === "chara_name" || name === "chara_ptext") && typeof pm.name === "string") pm.name = translateText(pm.name, name);
            }
          } catch (error) {
            logDiag("patch " + sourceName + "." + name + " failed: " + String(error && (error.stack || error.message) || error));
          }
          return oldStart.apply(this, arguments);
        };
        tag._rpgmtransPatched = true;
        changed = true;
      });
      return changed;
    }
    if (window.tyrano && window.tyrano.plugin && window.tyrano.plugin.kag) {
      patchedAny = patchTagSet(window.tyrano.plugin.kag.tag, "tyrano.plugin.kag.tag") || patchedAny;
    }
    var kag = window.TYRANO && window.TYRANO.kag;
    if (kag && kag.ftag) {
      patchedAny = patchTagSet(kag.ftag.master_tag, "TYRANO.kag.ftag.master_tag") || patchedAny;
    }
    return patchedAny;
  }

  function walkTextNodes(rootNode, visitor) {
    if (!rootNode) return;
    if (rootNode.nodeType === 3) {
      visitor(rootNode);
      return;
    }
    var children = rootNode.childNodes;
    if (!children) return;
    for (var i = 0; i < children.length; i++) walkTextNodes(children[i], visitor);
  }

  function refreshDomText() {
    walkTextNodes(document.body, function(node) {
      var source = node.nodeValue;
      var target = translateText(source, "dom", { recordMiss: false });
      if (target !== source) node.nodeValue = target;
    });
  }

  function startObserver() {
    if (!window.MutationObserver || !document.body) return;
    var observer = new MutationObserver(function() { refreshDomText(); });
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
  }

  var patched = false;
  var timer = setInterval(function() {
    var reloaded = reloadCacheIfNeeded(false);
    if (reloaded) repaintPendingDialogue();
    if (!patched) patched = patchTyranoTags();
    refreshDomText();
  }, 250);
  setTimeout(startObserver, 1000);
  reloadCacheIfNeeded(true);
})();`;
