export function buildTyranoRuntimePlugin(targetLang: string): string {
  return PLUGIN.replace("__RPGMTRANS_TARGET_LANG__", JSON.stringify(targetLang));
}

const PLUGIN = String.raw`// RPGMTransRuntime bridge for TyranoScript.
// Generated by RPGMTransCompiler. It never calls external APIs.
(function() {
  "use strict";

  var ENGINE = "TYRANO";
  var TARGET_LANG = __RPGMTRANS_TARGET_LANG__;
  var PROTOCOL = "1";
  var CACHE_RELOAD_MS = 250;

  var fs = null;
  var path = null;
  try {
    fs = require("fs");
    path = require("path");
  } catch (error) {
    return;
  }

  var root = process.cwd();
  var runtimeDir = path.join(root, "RPGMTransRuntime");
  var requestDir = path.join(runtimeDir, "requests");
  var cacheFile = path.join(runtimeDir, "cache", "translations.rtc");
  var diagDir = path.join(runtimeDir, "diag");
  var sessionFile = path.join(requestDir, "session-" + Date.now() + "-" + Math.floor(Math.random() * 1000000) + ".rtlog");
  var cacheMtime = 0;
  var lastCacheCheck = 0;
  var translations = Object.create(null);
  var seen = Object.create(null);

  function mkdirp(dir) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  }

  mkdirp(requestDir);
  mkdirp(path.dirname(cacheFile));
  mkdirp(diagDir);
  if (!fs.existsSync(cacheFile)) fs.writeFileSync(cacheFile, "# RPGMTransRuntime cache v1\n", "utf8");
  fs.appendFileSync(sessionFile, "# RPGMTransRuntime requests v1\n", "utf8");

  function runtimeHash(input) {
    var bytes = Buffer.from(String(input), "utf8");
    var seeds = [0x811c9dc5, 0x1f123bb5, 0x9e3779b9, 0x85ebca6b];
    var out = [];
    for (var s = 0; s < seeds.length; s++) {
      var hash = seeds[s] >>> 0;
      for (var i = 0; i < bytes.length; i++) {
        hash ^= bytes[i];
        hash = Math.imul(hash, 0x01000193) >>> 0;
      }
      out.push(("00000000" + hash.toString(16)).slice(-8));
    }
    return out.join("");
  }

  function hex(input) {
    return Buffer.from(String(input), "utf8").toString("hex");
  }

  function unhex(input) {
    return Buffer.from(String(input), "hex").toString("utf8");
  }

  function normalizeText(input) {
    return String(input == null ? "" : input).replace(/\r\n/g, "\n").replace(/\r/g, "\n").replace(/[ \t]+/g, " ").trim();
  }

  function shouldRecordText(input) {
    var text = normalizeText(input);
    if (!text) return false;
    if (text.indexOf("[" + TARGET_LANG + "]") === 0) return false;
    var ascii = /^[\x00-\x7f]+$/.test(text);
    if (ascii && text.length === 1) return false;
    if (ascii && !/[A-Za-z]/.test(text)) return false;
    return true;
  }

  function placeholderSignature(input) {
    var text = String(input);
    var re = /\[[A-Za-z_][A-Za-z0-9_]*(?:\s+[^\]\r\n]{0,240})?\]|\{\/?[A-Za-z][A-Za-z0-9_]*(?:=[^{}\r\n]{0,120})?\}|[\\\x1b¥￥][VvNnPpCcIiSs]\[\d+\]|[\\\x1b¥￥][A-Za-z]{1,12}\[[^\]\r\n]{0,80}\]|[\\\x1b¥￥][Gg.!|><^{}\\]|#\{[^}]*\}|\$\{[^}]*\}|%(?:\d+\$)?[-+#0 ]*(?:\d+|\*)?(?:\.(?:\d+|\*))?[bcdeEufFgGosxX]|%\d+|<\/?[A-Za-z][^>\n]{0,120}>|\{\{[^{}\n]{1,80}\}\}/g;
    var out = [];
    var match;
    while ((match = re.exec(text))) out.push(hex(match[0]));
    return out.length ? out.join(",") : "none";
  }

  function textKey(source) {
    var normalized = normalizeText(source);
    return "tk_" + runtimeHash([
      "rpgmtrans-runtime-text-v1",
      ENGINE,
      TARGET_LANG,
      normalized,
      placeholderSignature(normalized)
    ].join("\n"));
  }

  function surfaceKey(source, hook, scene, windowName, width, align) {
    var tk = textKey(source);
    return "sk_" + runtimeHash([
      "rpgmtrans-runtime-surface-v1",
      tk,
      hook,
      scene || "",
      windowName || "",
      String(width || ""),
      align || ""
    ].join("\n"));
  }

  function parseCache() {
    var map = Object.create(null);
    if (!fs.existsSync(cacheFile)) return map;
    var lines = fs.readFileSync(cacheFile, "utf8").split(/\r?\n/);
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      if (!line || line.charAt(0) === "#") continue;
      var parts = line.split("\t");
      if (parts.length < 11 || parts[0] !== "1") continue;
      map[parts[2]] = { sourceHex: parts[7], target: unhex(parts[8]) };
    }
    return map;
  }

  function reloadCacheIfNeeded(force) {
    var now = Date.now();
    if (!force && now - lastCacheCheck < CACHE_RELOAD_MS) return false;
    lastCacheCheck = now;
    try {
      var stat = fs.existsSync(cacheFile) ? fs.statSync(cacheFile) : null;
      var mtime = stat ? stat.mtimeMs : 0;
      if (!force && mtime === cacheMtime) return false;
      cacheMtime = mtime;
      translations = parseCache();
      return true;
    } catch (error) {
      try { fs.appendFileSync(path.join(diagDir, "plugin.log"), String(error.stack || error) + "\n", "utf8"); } catch (_) {}
      return false;
    }
  }

  function lookup(source, sk, tk) {
    reloadCacheIfNeeded(false);
    var sourceHex = hex(source);
    var surface = translations[sk];
    if (surface && surface.sourceHex === sourceHex) return surface.target;
    var text = translations[tk];
    if (text && text.sourceHex === sourceHex) return text.target;
    return null;
  }

  function record(source, hook, width, align) {
    var normalized = normalizeText(source);
    if (!shouldRecordText(source)) return source;
    var tk = textKey(source);
    var sk = surfaceKey(source, hook, "", "", width || "", align || "");
    var target = lookup(source, sk, tk);
    if (target != null) return target;
    if (!seen[sk]) {
      seen[sk] = true;
      var line = [
        PROTOCOL,
        ENGINE,
        TARGET_LANG,
        tk,
        sk,
        hook,
        "",
        "",
        String(width || ""),
        String(align || ""),
        hex(normalized),
        hex(source),
        placeholderSignature(normalized),
        new Date().toISOString()
      ].join("\t") + "\n";
      try { fs.appendFileSync(sessionFile, line, "utf8"); } catch (error) {}
    }
    return source;
  }

  function translateText(value, hook) {
    if (typeof value !== "string") return value;
    return record(value, hook || "tyrano", "", "");
  }

  function patchTyranoTags() {
    var kag = window.TYRANO && window.TYRANO.kag;
    if (!kag || !kag.ftag || !kag.ftag.master_tag) return false;
    var tags = kag.ftag.master_tag;
    ["text", "ptext", "glink", "button", "link", "chara_name"].forEach(function(name) {
      var tag = tags[name];
      if (!tag || tag._rpgmtransPatched || typeof tag.start !== "function") return;
      var oldStart = tag.start;
      tag.start = function(pm) {
        try {
          if (pm) {
            if (typeof pm.text === "string") pm.text = translateText(pm.text, name);
            if (name === "chara_name" && typeof pm.name === "string") pm.name = translateText(pm.name, name);
          }
        } catch (error) {}
        return oldStart.apply(this, arguments);
      };
      tag._rpgmtransPatched = true;
    });
    return true;
  }

  function walkTextNodes(rootNode, visitor) {
    if (!rootNode) return;
    if (rootNode.nodeType === 3) {
      visitor(rootNode);
      return;
    }
    var children = rootNode.childNodes;
    if (!children) return;
    for (var i = 0; i < children.length; i++) walkTextNodes(children[i], visitor);
  }

  function refreshDomText() {
    walkTextNodes(document.body, function(node) {
      var source = node.nodeValue;
      var target = translateText(source, "dom");
      if (target !== source) node.nodeValue = target;
    });
  }

  function startObserver() {
    if (!window.MutationObserver || !document.body) return;
    var observer = new MutationObserver(function() { refreshDomText(); });
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
  }

  var patched = false;
  var timer = setInterval(function() {
    reloadCacheIfNeeded(false);
    if (!patched) patched = patchTyranoTags();
    refreshDomText();
  }, 250);
  setTimeout(startObserver, 1000);
  reloadCacheIfNeeded(true);
})();`;
