#!/usr/bin/env python3
"""Best-effort Ren'Py script preparation helper for RPGMTransCompiler.

This helper is intentionally read-only with respect to the game directory. It
extracts script-like files from RPA archives and produces synthetic .rpy text
dumps from compiled .rpyc/.rpymc payloads so the TypeScript pretranslator can
collect visible text candidates without launching the game.
"""

from __future__ import annotations

import json
import os
import pickle
import pickletools
import re
import sys
import zlib
from pathlib import Path
from typing import Iterable


VERSION = "rpgmtrans-renpy-helper-v2"
SCRIPT_EXTS = (".rpy", ".rpyc", ".rpymc")
TEXT_RE = re.compile(r"[A-Za-z\u3040-\u30ff\u3400-\u9fff]")
RESOURCE_RE = re.compile(r"^[A-Za-z0-9_./\\:-]+\.(png|jpg|jpeg|webp|ogg|opus|mp3|wav|rpy|rpyc|rpymc|rpa)$", re.I)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(json.dumps({"ok": False, "error": "missing command"}))
        return 2
    command = argv[1]
    try:
        if command == "dump-rpyc":
            if len(argv) != 4:
                raise ValueError("usage: dump-rpyc INPUT OUTPUT")
            result = dump_rpyc(Path(argv[2]), Path(argv[3]))
        elif command == "extract-rpa":
            if len(argv) != 4:
                raise ValueError("usage: extract-rpa INPUT OUTPUT_DIR")
            result = extract_rpa(Path(argv[2]), Path(argv[3]))
        else:
            raise ValueError("unknown command: " + command)
        print(json.dumps({"ok": True, **result}, ensure_ascii=False))
        return 0
    except Exception as error:
        print(json.dumps({"ok": False, "error": str(error)}, ensure_ascii=False))
        return 1


def dump_rpyc(source: Path, output: Path) -> dict[str, object]:
    data = source.read_bytes()
    exact_payloads = parse_rpyc_payloads(data)
    payloads = exact_payloads if exact_payloads else list(decompressed_payloads(data))
    strings: list[str] = []
    seen: set[str] = set()
    for payload in payloads:
        for text in extract_pickle_strings(payload):
            if text not in seen:
                seen.add(text)
                strings.append(text)
        if not exact_payloads:
            for text in extract_binary_strings(payload):
                if text not in seen:
                    seen.add(text)
                    strings.append(text)

    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Decompiled text dump generated by RPGMTransCompiler.",
        "# This is not game source and must not be written back to the game directory.",
        f"# helper: {VERSION}",
        f"# source: {source.as_posix()}",
        "_rpgmtrans_compiled_texts = [",
    ]
    for text in strings:
        lines.append("    " + repr(text) + ",")
    lines.append("]")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {"output": str(output), "strings": len(strings), "payloads": len(payloads), "exact": bool(exact_payloads)}


def parse_rpyc_payloads(data: bytes) -> list[bytes]:
    if not data.startswith(b"RENPY RPC"):
        return []
    offset = 10
    payloads: list[bytes] = []
    while offset + 12 <= len(data):
        slot = int.from_bytes(data[offset:offset + 4], "little")
        start = int.from_bytes(data[offset + 4:offset + 8], "little")
        length = int.from_bytes(data[offset + 8:offset + 12], "little")
        offset += 12
        if slot == 0 and start == 0 and length == 0:
            break
        if start < 0 or length <= 0 or start + length > len(data):
            continue
        try:
            payloads.append(zlib.decompress(data[start:start + length]))
        except Exception:
            continue
    return payloads


def decompressed_payloads(data: bytes) -> Iterable[bytes]:
    yielded: set[bytes] = set()
    for payload in (data,):
        yielded.add(payload)
        yield payload

    # Ren'Py compiled scripts commonly contain zlib-compressed pickle chunks.
    # Brute-scanning zlib headers is more tolerant than relying on one exact
    # RPYC header variant.
    for offset in range(0, len(data) - 2):
        if data[offset] != 0x78:
            continue
        try:
            payload = zlib.decompress(data[offset:])
        except Exception:
            continue
        if len(payload) < 8 or payload in yielded:
            continue
        yielded.add(payload)
        yield payload


def extract_pickle_strings(payload: bytes) -> Iterable[str]:
    try:
        for opcode, arg, _pos in pickletools.genops(payload):
            if isinstance(arg, str) and likely_text(arg):
                yield arg
            elif isinstance(arg, bytes):
                text = decode_bytes(arg)
                if text and likely_text(text):
                    yield text
    except Exception:
        return


def extract_binary_strings(payload: bytes) -> Iterable[str]:
    for match in re.finditer(rb"[\x09\x0a\x0d\x20-\x7e\xc2-\xf4][\x09\x0a\x0d\x20-\x7e\x80-\xbf]{1,400}", payload):
        text = decode_bytes(match.group(0))
        if text and likely_text(text):
            yield text


def decode_bytes(value: bytes) -> str | None:
    for encoding in ("utf-8",):
        try:
            text = value.decode(encoding).strip()
        except Exception:
            continue
        if text:
            return text
    return None


def likely_text(text: str) -> bool:
    value = text.strip()
    if len(value) < 2 or len(value) > 1000:
        return False
    if "\x00" in value:
        return False
    if not TEXT_RE.search(value):
        return False
    if RESOURCE_RE.match(value):
        return False
    if value.startswith(("renpy.", "config.", "style.", "store.", "__")):
        return False
    if value.startswith(("RENPY RPC", "RPYC", "RPA-")):
        return False
    if re.match(r"^[A-Za-z_][A-Za-z0-9_]{1,48}$", value):
        return False
    return True


def extract_rpa(source: Path, output_dir: Path) -> dict[str, object]:
    data = source.read_bytes()
    first_line, header_size = read_header(data)
    parts = first_line.split()
    if len(parts) < 2 or not parts[0].startswith("RPA-"):
        raise ValueError("not a supported RPA archive")
    version = parts[0]
    index_offset = int(parts[1], 16)
    key = int(parts[2], 16) if version.startswith("RPA-3") and len(parts) >= 3 else 0
    if index_offset < header_size or index_offset >= len(data):
        raise ValueError("invalid RPA index offset")
    index = pickle.loads(zlib.decompress(data[index_offset:]))
    output_dir.mkdir(parents=True, exist_ok=True)
    extracted = 0
    for name, entries in index.items():
        normalized = str(name).replace("\\", "/")
        if not normalized.lower().endswith(SCRIPT_EXTS):
            continue
        if normalized.startswith("../") or os.path.isabs(normalized):
            continue
        if not isinstance(entries, (list, tuple)):
            continue
        for entry_index, entry in enumerate(entries):
            if not isinstance(entry, (list, tuple)) or len(entry) < 2:
                continue
            offset = int(entry[0]) ^ key
            length = int(entry[1]) ^ key
            prefix = entry[2] if len(entry) >= 3 and isinstance(entry[2], bytes) else b""
            if offset < 0 or length < 0 or offset + length > len(data):
                continue
            target = output_dir / normalized
            if entry_index:
                target = target.with_name(target.name + f".{entry_index}")
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(prefix + data[offset:offset + length])
            extracted += 1
    return {"output": str(output_dir), "files": extracted}


def read_header(data: bytes) -> tuple[str, int]:
    newline = data.find(b"\n")
    if newline < 0:
        raise ValueError("archive header is missing")
    return data[:newline].decode("ascii", "replace").strip(), newline + 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
