# RPGMTransRuntime bridge. Generated by RPGMTransCompiler.
# This script records displayed text and hot-loads local translations.

module RPGMTransRuntime
  VERSION = "1"
  ENGINE = "__RPGMTRANS_ENGINE__"
  TARGET_LANG = "__RPGMTRANS_TARGET_LANG__"
  CACHE_RELOAD_SECONDS = 0.25

  # RGSS3 on Windows is fragile with non-ASCII absolute paths. Keep all runtime
  # IO relative to the game working directory so directories like "副本" do not
  # prevent request/cache files from being opened.
  @runtime_dir = "RPGMTransRuntime"
  @request_dir = File.join(@runtime_dir, "requests")
  @cache_file = File.join(@runtime_dir, "cache", "translations.rtc")
  @diag_dir = File.join(@runtime_dir, "diag")
  @session_file = File.join(@request_dir, "session-#{Time.now.to_i}-#{rand(1000000)}.rtlog")
  @cache_mtime = nil
  @last_cache_check = Time.at(0)
  @translations = {}
  @seen = {}
  @dirty_refresh = false
  @drawing = false
  @current_message_window = nil

  class << self
    attr_accessor :drawing
    attr_accessor :current_message_window
  end

  def self.mkdir_p(dir)
    return if File.directory?(dir)
    parent = File.dirname(dir)
    mkdir_p(parent) if parent && parent != dir && !File.directory?(parent)
    Dir.mkdir(dir) unless File.directory?(dir)
  end

  def self.read_file(file)
    File.open(file, "rb") { |handle| handle.read }
  end

  def self.append_file(file, text)
    File.open(file, "ab") { |handle| handle.write(text) }
  rescue
  end

  def self.write_file(file, text)
    File.open(file, "wb") { |handle| handle.write(text) }
  end

  def self.setup
    mkdir_p(@request_dir)
    mkdir_p(File.dirname(@cache_file))
    mkdir_p(@diag_dir)
    write_file(@cache_file, "# RPGMTransRuntime cache v1\n") unless File.file?(@cache_file)
    append_file(@session_file, "# RPGMTransRuntime requests v1\n")
    reload_cache(true)
  rescue Exception => e
    log_error(e)
  end

  def self.log_error(error)
    append_file(File.join(@diag_dir, "plugin.log"), "#{error.class}: #{error.message}\n")
  rescue
  end

  def self.runtime_hash(text)
    bytes = []
    text.to_s.each_byte { |byte| bytes << byte }
    seeds = [0x811c9dc5, 0x1f123bb5, 0x9e3779b9, 0x85ebca6b]
    seeds.map do |seed|
      hash = seed & 0xffffffff
      bytes.each do |byte|
        hash = (hash ^ byte) & 0xffffffff
        hash = (hash * 0x01000193) & 0xffffffff
      end
      ("%08x" % hash)
    end.join("")
  end

  def self.hex(text)
    text.to_s.unpack("H*")[0]
  end

  def self.unhex(text)
    value = [text.to_s].pack("H*")
    value.force_encoding("UTF-8") if value.respond_to?(:force_encoding)
    value
  end

  def self.normalize_text(text)
    text.to_s.gsub("\r\n", "\n").gsub("\r", "\n").gsub(/[ \t]+/, " ").strip
  end

  def self.visible_char_count_at_most?(text, limit)
    count = 0
    text.to_s.each_char do
      count += 1
      return false if count > limit
    end
    true
  rescue
    text.to_s.length <= limit
  end

  def self.should_record_text?(text)
    normalized = normalize_text(text)
    return false if normalized.empty?
    return false if normalized.index("[#{TARGET_LANG}]") == 0
    visible = normalized.gsub(/[\\\e][VvNnPpCcIiSs]\[\d+\]|[\\\e][A-Za-z]{1,12}\[[^\]\r\n]{0,80}\]/, "")
    visible.gsub!(/[\\\e][Gg.!|><^{}\\]/, "")
    return false if visible_char_count_at_most?(visible, 1)
    return false if normalized =~ /^[A-Za-z0-9_.\/\\:@%+\- ]+\.(png|jpe?g|webp|gif|bmp|ogg|m4a|mp3|wav|flac|json|js|css|html?|ttf|otf|woff2?|rgss3a)$/i
    return false if normalized =~ /^(?:[A-Za-z]:)?[A-Za-z0-9_. -]+(?:[\/\\][A-Za-z0-9_. -]+)+$/
    return false if normalized =~ /^<PH_\d+\/>$|^<\/?[A-Za-z][^>\n]{0,120}>$/
    return false if visible !~ /[A-Za-z0-9\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]/
    true
  end

  def self.placeholder_signature(text)
    regex = /[\\\e][VvNnPpCcIiSs]\[\d+\]|[\\\e][A-Za-z]{1,12}\[[^\]\r\n]{0,80}\]|[\\\e][Gg.!|><^{}\\]|#\{[^}]*\}|\$\{[^}]*\}|%(?:\d+\$)?[-+#0 ]*(?:\d+|\*)?(?:\.(?:\d+|\*))?[bcdeEufFgGosxX]|%\d+|<\/?[A-Za-z][^>\n]{0,120}>|\{\{[^{}\n]{1,80}\}\}|\{[A-Za-z_][A-Za-z0-9_.-]{0,80}\}/
    matches = []
    text.to_s.scan(regex) { |match| matches << hex(match) }
    matches.empty? ? "none" : matches.join(",")
  end

  def self.text_key(source)
    normalized = normalize_text(source)
    "tk_" + runtime_hash([
      "rpgmtrans-runtime-text-v1",
      ENGINE,
      TARGET_LANG,
      normalized,
      placeholder_signature(normalized)
    ].join("\n"))
  end

  def self.surface_key(source, hook, scene, window_name, width, align)
    tk = text_key(source)
    "sk_" + runtime_hash([
      "rpgmtrans-runtime-surface-v1",
      tk,
      hook.to_s,
      scene.to_s,
      window_name.to_s,
      width.to_s,
      align.to_s
    ].join("\n"))
  end

  def self.scene_name
    if defined?(SceneManager) && SceneManager.respond_to?(:scene) && SceneManager.scene
      SceneManager.scene.class.name.to_s
    elsif defined?($scene) && $scene
      $scene.class.name.to_s
    else
      ""
    end
  rescue
    ""
  end

  def self.window_name(window)
    window && window.class ? window.class.name.to_s : ""
  rescue
    ""
  end

  def self.reload_cache(force = false)
    now = Time.now
    return if !force && now - @last_cache_check < CACHE_RELOAD_SECONDS
    @last_cache_check = now
    mtime = File.file?(@cache_file) ? File.mtime(@cache_file) : nil
    return if !force && mtime == @cache_mtime
    @cache_mtime = mtime
    parsed = {}
    if File.file?(@cache_file)
      read_file(@cache_file).split(/\r?\n/).each do |line|
        next if line.nil? || line.empty? || line[0, 1] == "#"
        parts = line.split("\t")
        next unless parts.length >= 11 && parts[0] == "1"
        parsed[parts[2]] = { :source_hex => parts[7], :target => unhex(parts[8]) }
      end
    end
    @translations = parsed
    @dirty_refresh = true
  rescue Exception => e
    log_error(e)
  end

  def self.lookup(source, surface_key_value, text_key_value)
    reload_cache(false)
    source_hex = hex(source)
    surface = @translations[surface_key_value]
    return prepare_target_text(surface[:target]) if cache_source_matches?(surface, source, source_hex)
    text = @translations[text_key_value]
    return prepare_target_text(text[:target]) if cache_source_matches?(text, source, source_hex)
    nil
  end

  def self.cache_source_matches?(entry, source, source_hex)
    return false unless entry
    return true if entry[:source_hex] == source_hex
    normalize_text(unhex(entry[:source_hex])) == normalize_text(source)
  rescue
    false
  end

  def self.prepare_target_text(text)
    target = text.to_s.dup
    if TARGET_LANG.to_s.index("zh") == 0
      target = target.gsub(/([^\s])([\\\e][Ii]{1,2}\[\d+\])/, "\\1 \\2")
      target = target.gsub(/([\\\e][Ii]{1,2}\[\d+\])([^\s])/, "\\1 \\2")
    end
    target
  rescue
    text.to_s.dup
  end

  def self.translation_for(source, hook, window, width = "", align = "")
    return nil unless should_record_text?(source)
    scene = scene_name
    window_class = window_name(window)
    tk = text_key(source)
    sk = surface_key(source, hook, scene, window_class, width, align)
    lookup(source, sk, tk)
  rescue Exception => e
    log_error(e)
    nil
  end

  def self.record(source, hook, window, width = "", align = "")
    normalized = normalize_text(source)
    return nil unless should_record_text?(source)
    scene = scene_name
    window_class = window_name(window)
    tk = text_key(source)
    sk = surface_key(source, hook, scene, window_class, width, align)
    translated = lookup(source, sk, tk)
    return translated if translated
    unless @seen[sk]
      @seen[sk] = true
      line = [
        VERSION,
        ENGINE,
        TARGET_LANG,
        tk,
        sk,
        hook.to_s,
        scene,
        window_class,
        width.to_s,
        align.to_s,
        hex(normalized),
        hex(source),
        placeholder_signature(normalized),
        Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")
      ].join("\t") + "\n"
      append_file(@session_file, line)
    end
    nil
  rescue Exception => e
    log_error(e)
    nil
  end

  def self.refreshable_object?(object)
    object.respond_to?(:refresh) ||
      object.respond_to?(:rpgmtrans_runtime_repaint_if_translated) ||
      object.respond_to?(:instance_variables)
  rescue
    false
  end

  def self.with_draw_guard
    old = @drawing
    @drawing = true
    yield
  ensure
    @drawing = old
  end

  def self.refresh_object(object, visited)
    return if object.nil?
    id = object.object_id
    return if visited[id]
    visited[id] = true
    if object.respond_to?(:rpgmtrans_runtime_repaint_if_translated)
      begin
        object.rpgmtrans_runtime_repaint_if_translated
      rescue Exception => e
        log_error(e)
      end
    end
    if object.respond_to?(:refresh)
      begin
        object.refresh
      rescue
      end
    end
    return unless object.respond_to?(:instance_variables)
    object.instance_variables.each do |name|
      begin
        child = object.instance_variable_get(name)
        refresh_object(child, visited) if refreshable_object?(child)
        if child.is_a?(Array)
          child.each { |item| refresh_object(item, visited) if refreshable_object?(item) }
        elsif child.is_a?(Hash)
          child.each_value { |item| refresh_object(item, visited) if refreshable_object?(item) }
        end
      rescue
      end
    end
  end

  def self.refresh_if_dirty
    reload_cache(false)
    return unless @dirty_refresh
    @dirty_refresh = false
    window = @current_message_window
    return unless window && window.respond_to?(:rpgmtrans_runtime_repaint_if_translated)
    window.rpgmtrans_runtime_repaint_if_translated
  rescue Exception => e
    log_error(e)
  end

  def self.install_mouse_compat
    return unless defined?(Mouse)
    class << Mouse
      if method_defined?(:global_pos) && !method_defined?(:rpgmtrans_runtime_global_pos)
        alias rpgmtrans_runtime_global_pos global_pos
        def global_pos(*args)
          result = rpgmtrans_runtime_global_pos(*args)
          result && result.length >= 2 ? result : [0, 0]
        rescue
          [0, 0]
        end
      end

      if method_defined?(:screen_to_client) && !method_defined?(:rpgmtrans_runtime_screen_to_client)
        alias rpgmtrans_runtime_screen_to_client screen_to_client
        def screen_to_client(x = 0, y = 0, *args)
          result = rpgmtrans_runtime_screen_to_client(x || 0, y || 0, *args)
          result && result.length >= 2 ? result : [0, 0]
        rescue
          [0, 0]
        end
      end
    end
  rescue Exception => e
    log_error(e)
  end
end

RPGMTransRuntime.setup
RPGMTransRuntime.install_mouse_compat

if defined?(Graphics) && Graphics.respond_to?(:update)
  class << Graphics
    unless method_defined?(:rpgmtrans_runtime_update)
      alias rpgmtrans_runtime_update update
      def update(*args)
        RPGMTransRuntime.refresh_if_dirty
        rpgmtrans_runtime_update(*args)
      end
    end
  end
end

if defined?(Window_Base)
  class Window_Base
    if method_defined?(:draw_text) && !method_defined?(:rpgmtrans_runtime_draw_text)
      alias rpgmtrans_runtime_draw_text draw_text
      def draw_text(*args)
        if RPGMTransRuntime.drawing
          return rpgmtrans_runtime_draw_text(*args)
        end
        text_index = args[0].is_a?(Rect) ? 1 : 4
        text = args[text_index]
        width = args[0].is_a?(Rect) ? args[0].width : args[2]
        align = args[0].is_a?(Rect) ? args[2] : args[5]
        translated = RPGMTransRuntime.record(text, "draw_text", self, width, align)
        args[text_index] = translated if translated
        RPGMTransRuntime.with_draw_guard { rpgmtrans_runtime_draw_text(*args) }
      end
    end

    if method_defined?(:draw_text_ex) && !method_defined?(:rpgmtrans_runtime_draw_text_ex)
      alias rpgmtrans_runtime_draw_text_ex draw_text_ex
      def draw_text_ex(x, y, text, *rest)
        if RPGMTransRuntime.drawing
          return rpgmtrans_runtime_draw_text_ex(x, y, text, *rest)
        end
        width = respond_to?(:contents) && contents ? contents.width : ""
        translated = RPGMTransRuntime.record(text, "draw_text_ex", self, width, "")
        RPGMTransRuntime.with_draw_guard { rpgmtrans_runtime_draw_text_ex(x, y, translated || text, *rest) }
      end
    end
  end
end

if defined?(Window_Message)
  class Window_Message
    if method_defined?(:update) && !method_defined?(:rpgmtrans_runtime_update)
      alias rpgmtrans_runtime_update update
      def update(*args)
        RPGMTransRuntime.current_message_window = self
        rpgmtrans_runtime_update(*args)
      end
    end

    def rpgmtrans_runtime_capture_source_text
      return nil unless defined?($game_message) && $game_message
      if $game_message.respond_to?(:rpgmtrans_runtime_raw_all_text)
        $game_message.rpgmtrans_runtime_raw_all_text
      elsif $game_message.respond_to?(:all_text)
        $game_message.all_text
      elsif $game_message.respond_to?(:texts)
        rpgmtrans_runtime_join_message_lines($game_message.texts)
      else
        nil
      end
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
      nil
    end

    def rpgmtrans_runtime_capture_source_lines
      return [] unless defined?($game_message) && $game_message
      if $game_message.respond_to?(:rpgmtrans_runtime_raw_texts)
        $game_message.rpgmtrans_runtime_raw_texts.map { |text| text.to_s }
      elsif $game_message.instance_variable_defined?(:@texts)
        $game_message.instance_variable_get(:@texts).map { |text| text.to_s }
      else
        []
      end
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
      []
    end

    def rpgmtrans_runtime_message_width
      respond_to?(:contents) && contents ? contents.width : ""
    rescue
      ""
    end

    def rpgmtrans_runtime_join_message_lines(lines)
      return nil unless lines && lines.respond_to?(:map)
      values = lines.map { |line| line.to_s }
      return nil if values.empty?
      text = values.join("\n")
      text += "\n" if values.length > 1
      text
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
      nil
    end

    def rpgmtrans_runtime_split_message_translation(source_lines, translated)
      return nil unless translated
      text = translated.to_s.gsub("\r\n", "\n").gsub("\r", "\n")
      parts = text.split("\n", -1)
      parts.pop if parts.length > 1 && parts[-1].empty?
      return nil if parts.empty?
      return nil if source_lines && source_lines.length > 1 && parts.length < source_lines.length
      parts
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
      nil
    end

    def rpgmtrans_runtime_translate_message_lines(source_lines)
      return nil unless source_lines && source_lines.respond_to?(:map)
      lines = source_lines.map { |line| line.to_s }
      return nil if lines.empty?
      width = rpgmtrans_runtime_message_width
      changed = false
      rendered = lines.dup

      full_source = rpgmtrans_runtime_join_message_lines(lines)
      if full_source && lines.length > 1
        full_translated = RPGMTransRuntime.record(full_source, "message_all", self, width, "")
        split = rpgmtrans_runtime_split_message_translation(lines, full_translated)
        if split && split.length >= lines.length
          rendered = split
          changed = true
        end
      end

      unless changed
        rendered = lines.map do |line|
          translated = RPGMTransRuntime.record(line, "message_add", self, "", "")
          changed = true if translated
          translated || line
        end
      end

      changed ? rendered : nil
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
      nil
    end

    def rpgmtrans_runtime_prepare_vx_message_texts
      return unless defined?($game_message) && $game_message && $game_message.respond_to?(:texts)
      source_lines = $game_message.texts.map { |line| line.to_s }
      @rpgmtrans_runtime_source_lines = source_lines
      @rpgmtrans_runtime_source_text = rpgmtrans_runtime_join_message_lines(source_lines)
      translated_lines = rpgmtrans_runtime_translate_message_lines(source_lines)
      return unless translated_lines && translated_lines.length > 0
      $game_message.texts = translated_lines
      @rpgmtrans_runtime_rendered_text = rpgmtrans_runtime_join_message_lines(translated_lines)
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
    end

    def rpgmtrans_runtime_repaint_if_translated
      return false if @rpgmtrans_runtime_repaint_lock
      return false unless @rpgmtrans_runtime_source_text || @rpgmtrans_runtime_converted_text
      return false unless respond_to?(:contents) && contents
      return false if contents.respond_to?(:disposed?) && contents.disposed?
      return false if respond_to?(:visible) && !visible
      if respond_to?(:open?) && respond_to?(:close?) && close?
        return false
      end

      width = rpgmtrans_runtime_message_width
      translated = nil
      if @rpgmtrans_runtime_converted_text
        translated = RPGMTransRuntime.translation_for(
          @rpgmtrans_runtime_converted_text,
          "message_converted",
          self,
          width,
          ""
        )
        if translated && rpgmtrans_runtime_layout_risky_translation?(@rpgmtrans_runtime_converted_text, translated)
          translated = rpgmtrans_runtime_line_translation_for_display || translated
        end
      end
      if !translated && @rpgmtrans_runtime_source_text
        translated = RPGMTransRuntime.translation_for(
          @rpgmtrans_runtime_source_text,
          "message_all",
          self,
          width,
          ""
        )
      end
      translated ||= rpgmtrans_runtime_join_line_translations
      return false unless translated
      return false if translated == @rpgmtrans_runtime_rendered_text

      rpgmtrans_runtime_draw_message_text(translated)
      @rpgmtrans_runtime_rendered_text = translated
      true
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
      false
    end

    def rpgmtrans_runtime_join_line_translations
      lines = @rpgmtrans_runtime_source_lines || []
      return nil if lines.empty?
      complete = false
      rendered = lines.map do |line|
        translated = RPGMTransRuntime.translation_for(line, "message_add", self, "", "")
        complete = true if translated
        translated || line
      end
      return nil unless complete
      rendered.join("\n") + "\n"
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
      nil
    end

    def rpgmtrans_runtime_line_translation_for_display(*args, &block)
      lines = @rpgmtrans_runtime_source_lines || []
      return nil if lines.empty?
      changed = false
      rendered = lines.map do |line|
        translated = RPGMTransRuntime.translation_for(line, "message_add", self, "", "")
        changed = true if translated
        translated || line
      end
      return nil unless changed
      raw_text = rendered.join("\n") + "\n"
      rpgmtrans_runtime_convert_escape_characters(raw_text, *args, &block)
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
      nil
    end

    def rpgmtrans_runtime_line_count(text)
      text.to_s.gsub("\r\n", "\n").gsub("\r", "\n").split("\n", -1).length
    rescue
      1
    end

    def rpgmtrans_runtime_layout_risky_translation?(source, target)
      source_text = source.to_s
      target_text = target.to_s
      return false unless source_text.include?("\n")
      return true if rpgmtrans_runtime_line_count(target_text) < rpgmtrans_runtime_line_count(source_text)
      return true if source_text =~ /\n[ \t]{8,}[\\\e]/ && target_text !~ /\n[ \t]{8,}[\\\e]/
      false
    rescue
      false
    end

    def rpgmtrans_runtime_draw_message_text(text)
      @rpgmtrans_runtime_repaint_lock = true
      @rpgmtrans_runtime_static_draw = true
      render_text = text.to_s.dup
      RPGMTransRuntime.with_draw_guard do
        contents.clear if respond_to?(:contents) && contents
        draw_face($game_message.face_name, $game_message.face_index, 0, 0) if defined?($game_message) && $game_message && respond_to?(:draw_face)
        reset_font_settings if respond_to?(:reset_font_settings)
        rpgmtrans_runtime_draw_static_text_block(render_text)
      end
      @rpgmtrans_runtime_suppress_source_tail = true
    ensure
      @rpgmtrans_runtime_static_draw = false
      @rpgmtrans_runtime_repaint_lock = false
    end

    def rpgmtrans_runtime_draw_static_text_block(text)
      return unless respond_to?(:contents) && contents
      base_x = respond_to?(:new_line_x) ? new_line_x : 0
      line_y = 0
      height = respond_to?(:line_height) ? line_height : 24
      normalized = text.to_s.gsub("\r\n", "\n").gsub("\r", "\n")
      normalized = normalized.gsub(/\\n(?!\[)/, "\n")
      normalized.split("\n", -1).each do |line|
        rpgmtrans_runtime_draw_static_line(base_x, line_y, line, height)
        line_y += height
      end
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
    end

    def rpgmtrans_runtime_draw_static_line(x, y, line, height)
      return unless respond_to?(:contents) && contents
      rest = line.to_s.dup
      cursor_x = x
      while rest && rest.length > 0
        if rest.sub!(/\A[\\\e][Cc]\[(\d+)\]/, "")
          change_color(text_color($1.to_i)) if respond_to?(:change_color) && respond_to?(:text_color)
          next
        end
        if rest.sub!(/\A[\\\e][Ii]\[(\d+)\]/, "")
          draw_icon($1.to_i, cursor_x, y) if respond_to?(:draw_icon)
          cursor_x += 24
          next
        end
        if rest.sub!(/\A[\\\e][Gg.!|><^{}\\]/, "")
          next
        end
        if rest.sub!(/\A[\\\e][A-Za-z]{1,12}\[[^\]\r\n]{0,80}\]/, "")
          next
        end
        chunk = rest.slice!(/\A[^\\\e]+/)
        if chunk.nil? || chunk.empty?
          rest.slice!(0, 1)
          next
        end
        contents.draw_text(cursor_x, y, [contents.width - cursor_x, 1].max, height, chunk)
        begin
          cursor_x += contents.text_size(chunk).width
        rescue
          cursor_x += chunk.length * 12
        end
      end
    rescue Exception => e
      RPGMTransRuntime.log_error(e)
    end

    if method_defined?(:wait_for_one_character) && !method_defined?(:rpgmtrans_runtime_wait_for_one_character)
      alias rpgmtrans_runtime_wait_for_one_character wait_for_one_character
      def wait_for_one_character(*args)
        rpgmtrans_runtime_wait_for_one_character(*args)
      end
    end

    if method_defined?(:input_pause) && !method_defined?(:rpgmtrans_runtime_input_pause)
      alias rpgmtrans_runtime_input_pause input_pause
      def input_pause(*args)
        rpgmtrans_runtime_input_pause(*args)
      end
    end

    if method_defined?(:start_message) && !method_defined?(:rpgmtrans_runtime_start_message)
      alias rpgmtrans_runtime_start_message start_message
      def start_message(*args)
        begin
          RPGMTransRuntime.current_message_window = self
          text = rpgmtrans_runtime_capture_source_text
          RPGMTransRuntime.record(text, "message", self, contents ? contents.width : "", "") if text
          rpgmtrans_runtime_prepare_vx_message_texts
        rescue Exception => e
          RPGMTransRuntime.log_error(e)
        end
        rpgmtrans_runtime_start_message(*args)
      end
    end

    if method_defined?(:convert_escape_characters) && !method_defined?(:rpgmtrans_runtime_convert_escape_characters)
      alias rpgmtrans_runtime_convert_escape_characters convert_escape_characters
      def convert_escape_characters(text, *args, &block)
        converted = rpgmtrans_runtime_convert_escape_characters(text, *args, &block)
        return converted if @rpgmtrans_runtime_static_draw || RPGMTransRuntime.drawing
        if defined?($game_message) && $game_message && $game_message.respond_to?(:has_text?) && $game_message.has_text?
          @rpgmtrans_runtime_converted_text = converted.to_s.dup
          translated = RPGMTransRuntime.record(
            @rpgmtrans_runtime_converted_text,
            "message_converted",
            self,
            rpgmtrans_runtime_message_width,
            ""
          )
          if !translated && @rpgmtrans_runtime_source_text
            raw_translated = RPGMTransRuntime.translation_for(
              @rpgmtrans_runtime_source_text,
              "message_all",
              self,
              rpgmtrans_runtime_message_width,
              ""
            )
            translated = rpgmtrans_runtime_convert_escape_characters(raw_translated, *args, &block) if raw_translated
          end
          translated ||= rpgmtrans_runtime_line_translation_for_display(*args, &block)
          if translated
            if rpgmtrans_runtime_layout_risky_translation?(@rpgmtrans_runtime_converted_text, translated)
              translated = rpgmtrans_runtime_line_translation_for_display(*args, &block) || translated
            end
            @rpgmtrans_runtime_rendered_text = translated.to_s.dup
            @rpgmtrans_runtime_suppress_source_tail = false
            return translated.to_s.dup
          end
        end
        converted
      rescue Exception => e
        RPGMTransRuntime.log_error(e)
        rpgmtrans_runtime_convert_escape_characters(text, *args, &block)
      end
    end

    if method_defined?(:process_all_text) && !method_defined?(:rpgmtrans_runtime_process_all_text)
      alias rpgmtrans_runtime_process_all_text process_all_text
      def process_all_text(*args)
        RPGMTransRuntime.current_message_window = self
        @rpgmtrans_runtime_source_text = rpgmtrans_runtime_capture_source_text
        @rpgmtrans_runtime_source_lines = rpgmtrans_runtime_capture_source_lines
        @rpgmtrans_runtime_converted_text = nil
        @rpgmtrans_runtime_rendered_text = nil
        @rpgmtrans_runtime_suppress_source_tail = false
        rpgmtrans_runtime_process_all_text(*args)
      end
    end

    if method_defined?(:process_normal_character) && !method_defined?(:rpgmtrans_runtime_process_normal_character)
      alias rpgmtrans_runtime_process_normal_character process_normal_character
      def process_normal_character(c, pos)
        return super(c, pos) if @rpgmtrans_runtime_static_draw
        if @rpgmtrans_runtime_suppress_source_tail
          wait_for_one_character if respond_to?(:wait_for_one_character)
          return
        end
        rpgmtrans_runtime_process_normal_character(c, pos)
      end
    end

    if method_defined?(:process_new_line) && !method_defined?(:rpgmtrans_runtime_process_new_line)
      alias rpgmtrans_runtime_process_new_line process_new_line
      def process_new_line(text, pos)
        return super(text, pos) if @rpgmtrans_runtime_static_draw
        rpgmtrans_runtime_process_new_line(text, pos)
      end
    end

    if method_defined?(:process_new_page) && !method_defined?(:rpgmtrans_runtime_process_new_page)
      alias rpgmtrans_runtime_process_new_page process_new_page
      def process_new_page(text, pos)
        if @rpgmtrans_runtime_static_draw
          text.slice!(/^\n/) if text.respond_to?(:slice!)
          return process_new_line(text, pos)
        end
        rpgmtrans_runtime_process_new_page(text, pos)
      end
    end

    if method_defined?(:process_escape_character) && !method_defined?(:rpgmtrans_runtime_process_escape_character)
      alias rpgmtrans_runtime_process_escape_character process_escape_character
      def process_escape_character(code, text, pos)
        if @rpgmtrans_runtime_static_draw
          return if ["$", ".", "|", "!", ">", "<", "^"].include?(code.to_s.upcase)
          return super(code, text, pos)
        end
        rpgmtrans_runtime_process_escape_character(code, text, pos)
      end
    end
  end
end

if defined?(Game_Message)
  class Game_Message
    if method_defined?(:clear) && !method_defined?(:rpgmtrans_runtime_clear)
      alias rpgmtrans_runtime_clear clear
      def clear(*args)
        @rpgmtrans_runtime_raw_texts = []
        rpgmtrans_runtime_clear(*args)
      end
    end

    def rpgmtrans_runtime_raw_texts
      @rpgmtrans_runtime_raw_texts ||= []
    end

    def rpgmtrans_runtime_raw_all_text
      rpgmtrans_runtime_raw_texts.inject("") { |result, text| result += text.to_s + "\n" }
    end

    if method_defined?(:add) && !method_defined?(:rpgmtrans_runtime_add)
      alias rpgmtrans_runtime_add add
      def add(text)
        begin
          source = text.to_s
          rpgmtrans_runtime_raw_texts << source
          RPGMTransRuntime.record(source, "message_add", self, "", "")
          rpgmtrans_runtime_add(text)
        rescue Exception => e
          RPGMTransRuntime.log_error(e)
          rpgmtrans_runtime_add(text)
        end
      end
    end

    if method_defined?(:new_page) && !method_defined?(:rpgmtrans_runtime_new_page)
      alias rpgmtrans_runtime_new_page new_page
      def new_page(*args)
        begin
          texts = rpgmtrans_runtime_raw_texts
          texts[-1] = texts[-1].to_s + "\f" if texts.size > 0
        rescue Exception => e
          RPGMTransRuntime.log_error(e)
        end
        rpgmtrans_runtime_new_page(*args)
      end
    end

    if method_defined?(:all_text) && !method_defined?(:rpgmtrans_runtime_all_text)
      alias rpgmtrans_runtime_all_text all_text
      def all_text(*args)
        source = respond_to?(:rpgmtrans_runtime_raw_all_text) ? rpgmtrans_runtime_raw_all_text : rpgmtrans_runtime_all_text(*args)
        RPGMTransRuntime.record(source, "message_all", self, "", "") if source && source.to_s.include?("\n")
        rpgmtrans_runtime_all_text(*args)
      rescue Exception => e
        RPGMTransRuntime.log_error(e)
        rpgmtrans_runtime_all_text(*args)
      end
    end
  end
end

if defined?(Bitmap)
  class Bitmap
    if method_defined?(:draw_text) && !method_defined?(:rpgmtrans_runtime_draw_text)
      alias rpgmtrans_runtime_draw_text draw_text
      def draw_text(*args)
        if RPGMTransRuntime.drawing
          return rpgmtrans_runtime_draw_text(*args)
        end
        text_index = args[0].is_a?(Rect) ? 1 : 4
        text = args[text_index]
        width = args[0].is_a?(Rect) ? args[0].width : args[2]
        align = args[0].is_a?(Rect) ? args[2] : args[5]
        translated = RPGMTransRuntime.record(text, "bitmap", self, width, align)
        args[text_index] = translated if translated
        rpgmtrans_runtime_draw_text(*args)
      end
    end
  end
end
